name: Deploy production
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: deploy-prod
        run: curl -X POST -d '{}' https://api.netlify.com/build_hooks/62e140692faa7022a6d6337b
